Fix package reference in version code
The package version file erroneously contained quotes here:

version_info = pbr.version.VersionInfo('__package__')

This caused docs builds using setuptools at or beyond 20.2 to fail with:

pkg_resources.RequirementParseError: Invalid requirement, parse error at
"'__packag'"

This change set remedies the line to refer to __package__ (a builtin
variable which resolves to the package name) rather than the literal
string '__package__':

version_info = pbr.version.VersionInfo(__package__)

...and updates the requirements file to use a setuptools version at or
beyond 16.0 to align with openstack's global requirements.

Change-Id: Iff8d31526ce485277530da9ab90bd6fbe2d31ecf
Closes-Bug: 1585027