Remove pycodestyle requirement
pycodestyle is added both to nova's and nova-powervm's
test-requirements.txt and need to be aligned or removed, otherwise the
unit test jobs fail with:

ERROR: Double requirement given: pycodestyle<2.6.0,>=2.0.0 (from -r https://opendev.org/openstack/nova/raw/branch/stable/train/test-requirements.txt (line 14)) (already in pycodestyle>=2.0.0 (from -r /home/zuul/src/opendev.org/openstack/nova-powervm/test-requirements.txt (line 15)), name='pycodestyle')

Patch Id564eea41e293872dc299f50e159c66d0d3e661e modified pycodestyle's
requirement in nova.

Change-Id: I92220f5828b72817e1cbe0d9201e3417a52893ed