Init UUIDCache in test_instance_exists
Depending on the order in which tox runs tests,
nova-powervm.tests.virt.powervm.test_vm.TestVM.test_instance_exists can
fail *intermittently* with:

Traceback (most recent call last):
  File "/home/jenkins/workspace/gate-nova-powervm-python27/.tox/py27/
local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "nova_powervm/tests/virt/powervm/test_vm.py", line 289, in
test_instance_exists
    self.assertTrue(vm.instance_exists(*mock_parms))
  File "nova_powervm/virt/powervm/vm.py", line 229, in instance_exists
    uuid = cache.lookup(instance.name, fetch=False)
AttributeError: 'NoneType' object has no attribute 'lookup'

...because UUIDCache needs to be initialized (by calling its
constructor) before it is used.

The reliable way to reproduce the problem is to run this test case by
itself, e.g.

tox -e py27 -- nova-powervm.tests.virt.powervm.test_vm.TestVM.test_inst
ance_exists

Change-Id: I6584a8e390d0cc8d8bfe0b7de476d4c37de11a64